<?php

class qTestBatch extends qBatchAbstract {

    public function __construct($batchRecord)
    {
        parent::__construct($batchRecord); // TODO: Change the autogenerated stub
    }

    public function work() {
        $lp = $this->getAttr('a', 0);
        $lp++;
        $msg = 'Indeksowanie plików, poczekaj ...';
        if ($lp < 10) {
            $msg = 'Indeksowanie plików: ' . $lp . ', poczekaj....';
            $this->setAttr('a', $lp);
            $this->setMessage($msg);
            $this->addRaport($msg);

            return false;
        }
        $msg = 'Indeksowanie plików: KONIEC';
        $this->setMessage($msg);

        return true;
    }


}